import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import { buildApp } from '../src/app.js';

let app: Awaited<ReturnType<typeof buildApp>>['app']; let dir: string; let receiverToken: string; let senderSecret: string; let roomId: string;
const pubkey = 'MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEtest';
async function createRoom() { const res = await app.inject({ method:'POST', url:'/api/rooms', headers:{'x-registration-secret':'reg'}, payload:{pubkey} }); assert.equal(res.statusCode,201); ({room_id: roomId, receiver_token: receiverToken, sender_secret: senderSecret} = res.json()); }
async function upload(id=randomUUID(), ttl=3600, maxViews=2) { return app.inject({ method:'PUT', url:`/api/photos/${id}`, headers:{authorization:`Bearer ${senderSecret}`,'x-room-id':roomId,'x-max-views':String(maxViews),'x-ttl-seconds':String(ttl),'content-type':'application/octet-stream'}, payload:Buffer.alloc(100, 7) }); }
const receiverHeaders = () => ({authorization:`Bearer ${receiverToken}`,'x-room-id':roomId});

before(async () => { dir = await mkdtemp(`${tmpdir()}/secure-photo-`); ({app} = await buildApp({dbFile:`${dir}/db.sqlite`,dataDir:`${dir}/files`,registrationSecret:'reg',maxRooms:1})); await createRoom(); });
after(async () => { await app.close(); await rm(dir,{recursive:true,force:true}); });

test('health, auth and max rooms', async () => { assert.equal((await app.inject('/healthz')).statusCode,200); assert.equal((await app.inject({method:'POST',url:'/api/rooms',headers:{'x-registration-secret':'wrong'},payload:{pubkey}})).statusCode,401); assert.equal((await app.inject({method:'POST',url:'/api/rooms',headers:{'x-registration-secret':'reg'},payload:{pubkey}})).statusCode,409); });
test('upload, list, idempotent open and view limit', async () => { const id=randomUUID(); assert.equal((await upload(id,3600,2)).statusCode,201); assert.equal((await upload(id,3600,2)).statusCode,409); const list=await app.inject({method:'GET',url:'/api/photos',headers:receiverHeaders()}); assert.equal(list.statusCode,200); assert.equal(list.json().find((x:any)=>x.id===id).views_used,0); const openId=randomUUID(); const one=await app.inject({method:'POST',url:`/api/photos/${id}/open`,headers:{...receiverHeaders(),'x-open-id':openId}}); assert.equal(one.statusCode,200); const repeat=await app.inject({method:'POST',url:`/api/photos/${id}/open`,headers:{...receiverHeaders(),'x-open-id':openId}}); assert.equal(repeat.statusCode,200); assert.deepEqual(repeat.rawPayload,one.rawPayload); const two=await app.inject({method:'POST',url:`/api/photos/${id}/open`,headers:{...receiverHeaders(),'x-open-id':randomUUID()}}); assert.equal(two.statusCode,200); const gone=await app.inject({method:'POST',url:`/api/photos/${id}/open`,headers:{...receiverHeaders(),'x-open-id':randomUUID()}}); assert.equal(gone.statusCode,410); });
test('parallel last opens allow exactly one', async () => { const id=randomUUID(); assert.equal((await upload(id,3600,1)).statusCode,201); const results=await Promise.all([0,1].map(()=>app.inject({method:'POST',url:`/api/photos/${id}/open`,headers:{...receiverHeaders(),'x-open-id':randomUUID()}}))); assert.deepEqual(results.map(r=>r.statusCode).sort(),[200,410]); });
test('TTL and invalid headers', async () => { const id=randomUUID(); assert.equal((await upload(id,60,0)).statusCode,201); const bad=await app.inject({method:'PUT',url:`/api/photos/${randomUUID()}`,headers:{authorization:`Bearer ${senderSecret}`,'x-room-id':roomId,'x-max-views':'1','x-ttl-seconds':'1','content-type':'application/octet-stream'},payload:Buffer.from('x'.repeat(100))}); assert.equal(bad.statusCode,400); assert.equal((await app.inject({method:'GET',url:'/api/photos',headers:{authorization:'Bearer bad','x-room-id':roomId}})).statusCode,401); });
test('sender secret rotation revokes the old secret', async () => { const old=senderSecret; const rotated=await app.inject({method:'POST',url:`/api/rooms/${roomId}/rotate-sender`,headers:receiverHeaders()}); assert.equal(rotated.statusCode,200); senderSecret=rotated.json().sender_secret; assert.notEqual(senderSecret,old); assert.equal((await upload(randomUUID())).statusCode,201); const oldUpload=await app.inject({method:'PUT',url:`/api/photos/${randomUUID()}`,headers:{authorization:`Bearer ${old}`,'x-room-id':roomId,'x-max-views':'1','x-ttl-seconds':'60','content-type':'application/octet-stream'},payload:Buffer.alloc(100,7)}); assert.equal(oldUpload.statusCode,401); });
